/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import com.formdev.flatlaf.*;
import org.jdesktop.swingx.prompt.*;

import javax.swing.*;
import javax.swing.border.*;
import java.awt.*;
import java.awt.event.*;
import java.io.*;

/**
 *
 * @author china
 */
public class MainMenu extends javax.swing.JFrame {

    public static final Color LIGHT_BG = new Color(245, 245, 245);
    public static final Color CARD_BG = new Color(255, 255, 255);

    public static final Color TEXT_PRIMARY = new Color(30, 30, 30);
    public static final Color TEXT_SECONDARY = new Color(90, 90, 90);
    public static final Color TEXT_DISABLED = new Color(150, 150, 150);

    public static final Color YouTube = new Color(251, 0, 50);
    public static final Color SPOTIFY = new Color(30, 215, 96);
    
    public static final Color HOVER = new Color(230, 230, 230);
    
    /** 
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setLocationRelativeTo(null);
        
        PromptSupport.setPrompt("Enter YouTube URL", yt_urlFld);
        PromptSupport.setForeground(TEXT_SECONDARY, yt_urlFld);
        
        transparentButton(yt_BrowseBtn);
        
    }
    
    public void transparentButton(JButton button) {
        button.setOpaque(false);
        button.setContentAreaFilled(false);
        button.setFocusPainted(false);
        button.setBorder(new LineBorder(HOVER, 1, true));
    }
    
    private void browseOutputDirectory(JTextField field) {
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(field.getText()));
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            field.setText(chooser.getSelectedFile().getAbsolutePath());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        HeaderPnl = new javax.swing.JPanel();
        TitlePanel = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        subTitle = new javax.swing.JLabel();
        TabbedPane = new javax.swing.JTabbedPane();
        YouTubePnl = new javax.swing.JPanel();
        YouTubeInputCard = new javax.swing.JPanel();
        yt_urlLbl = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        yt_urlFld = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(32767, 25));
        yt_OutputDirLbl = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        yt_DirPnl = new javax.swing.JPanel();
        yt_OutputDirFld = new javax.swing.JTextField();
        yt_BrowseBtn = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        yt_OptionsPnl = new javax.swing.JPanel();
        yt_PlaylistCheckBox = new javax.swing.JCheckBox();
        yt_AudioQualityComBox = new javax.swing.JComboBox<>();
        YouTubeControlCard = new javax.swing.JPanel();
        SpotifyPnl = new javax.swing.JPanel();
        SettingsPnl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(LIGHT_BG);

        MainPanel.setPreferredSize(new java.awt.Dimension(700, 900));
        MainPanel.setLayout(new java.awt.BorderLayout());

        HeaderPnl.setBackground(CARD_BG);
        HeaderPnl.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 30, 20, 30));
        HeaderPnl.setMinimumSize(new java.awt.Dimension(0, 0));
        HeaderPnl.setLayout(new java.awt.BorderLayout());

        TitlePanel.setBackground(CARD_BG);
        TitlePanel.setMinimumSize(new java.awt.Dimension(0, 0));
        TitlePanel.setName(""); // NOI18N
        TitlePanel.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        titleLbl.setFont(new java.awt.Font("JetBrains Mono", 1, 26)); // NOI18N
        titleLbl.setForeground(TEXT_PRIMARY);
        titleLbl.setText("SOUND BOX");
        TitlePanel.add(titleLbl);

        subTitle.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        subTitle.setForeground(TEXT_SECONDARY);
        subTitle.setText("Download high quality audio files from YouTube and Spotify");
        TitlePanel.add(subTitle);

        HeaderPnl.add(TitlePanel, java.awt.BorderLayout.WEST);

        MainPanel.add(HeaderPnl, java.awt.BorderLayout.NORTH);

        TabbedPane.setBackground(LIGHT_BG);
        TabbedPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 50, 10, 50));
        TabbedPane.setForeground(TEXT_PRIMARY);
        TabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabbedPane.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N

        YouTubePnl.setBackground(LIGHT_BG);
        YouTubePnl.setLayout(new java.awt.BorderLayout(0, 20));

        YouTubeInputCard.setBackground(CARD_BG        );
        YouTubeInputCard.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(HOVER, 1, true), javax.swing.BorderFactory.createEmptyBorder(25, 25, 25, 25)));
        YouTubeInputCard.setLayout(new javax.swing.BoxLayout(YouTubeInputCard, javax.swing.BoxLayout.Y_AXIS));

        yt_urlLbl.setFont(new java.awt.Font("JetBrains Mono ExtraBold", 1, 14)); // NOI18N
        yt_urlLbl.setText("YouTube URL");
        YouTubeInputCard.add(yt_urlLbl);
        YouTubeInputCard.add(filler1);

        yt_urlFld.setBackground(LIGHT_BG);
        yt_urlFld.setColumns(40);
        yt_urlFld.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        yt_urlFld.setForeground(TEXT_PRIMARY);
        yt_urlFld.setAlignmentX(0.0F);
        yt_urlFld.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(HOVER, 1, true), javax.swing.BorderFactory.createEmptyBorder(12, 15, 12, 15)));
        YouTubeInputCard.add(yt_urlFld);
        YouTubeInputCard.add(filler2);

        yt_OutputDirLbl.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        yt_OutputDirLbl.setForeground(TEXT_PRIMARY);
        yt_OutputDirLbl.setText("Output Folder");
        yt_OutputDirLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        YouTubeInputCard.add(yt_OutputDirLbl);
        YouTubeInputCard.add(filler4);

        yt_DirPnl.setBackground(CARD_BG);
        yt_DirPnl.setAlignmentX(0.0F);
        yt_DirPnl.setMaximumSize(new java.awt.Dimension(2147483647, 45));
        yt_DirPnl.setPreferredSize(new java.awt.Dimension(655, 45));
        yt_DirPnl.setLayout(new java.awt.BorderLayout(10, 0));

        yt_OutputDirFld.setColumns(40);
        yt_OutputDirFld.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        yt_OutputDirFld.setAlignmentX(0.0F);
        yt_OutputDirFld.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(HOVER, 1, true), javax.swing.BorderFactory.createEmptyBorder(12, 15, 12, 15)));
        yt_DirPnl.add(yt_OutputDirFld, java.awt.BorderLayout.CENTER);

        yt_BrowseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lightThemeIcon/folder.png"))); // NOI18N
        yt_BrowseBtn.setToolTipText("Browse");
        yt_BrowseBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 25, 12, 25));
        yt_BrowseBtn.setPreferredSize(new java.awt.Dimension(45, 45));
        yt_BrowseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yt_BrowseBtnActionPerformed(evt);
            }
        });
        yt_DirPnl.add(yt_BrowseBtn, java.awt.BorderLayout.EAST);
        yt_DirPnl.add(filler3, java.awt.BorderLayout.PAGE_START);

        YouTubeInputCard.add(yt_DirPnl);

        yt_OptionsPnl.setAlignmentX(0.0F);
        yt_OptionsPnl.setLayout(new java.awt.BorderLayout(10, 0));

        yt_PlaylistCheckBox.setBackground(CARD_BG);
        yt_PlaylistCheckBox.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        yt_PlaylistCheckBox.setForeground(TEXT_SECONDARY);
        yt_PlaylistCheckBox.setText("Download entire playlist");
        yt_PlaylistCheckBox.setFocusPainted(false);
        yt_OptionsPnl.add(yt_PlaylistCheckBox, java.awt.BorderLayout.WEST);

        yt_AudioQualityComBox.setBackground(CARD_BG);
        yt_AudioQualityComBox.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        yt_AudioQualityComBox.setForeground(TEXT_SECONDARY);
        yt_AudioQualityComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ultra  (320 kbps)", "High   (256 kbps)", "Medium (192 kbps)", "Low    (128 kbps)" }));
        yt_AudioQualityComBox.setAlignmentX(0.0F);
        yt_OptionsPnl.add(yt_AudioQualityComBox, java.awt.BorderLayout.EAST);

        YouTubeInputCard.add(yt_OptionsPnl);

        YouTubePnl.add(YouTubeInputCard, java.awt.BorderLayout.NORTH);

        YouTubeControlCard.setBackground(LIGHT_BG);
        YouTubeControlCard.setLayout(new javax.swing.BoxLayout(YouTubeControlCard, javax.swing.BoxLayout.X_AXIS));
        YouTubePnl.add(YouTubeControlCard, java.awt.BorderLayout.CENTER);

        TabbedPane.addTab("YouTube", new javax.swing.ImageIcon(getClass().getResource("/yt_music.png")), YouTubePnl, "YouTube"); // NOI18N

        SpotifyPnl.setBackground(LIGHT_BG);

        javax.swing.GroupLayout SpotifyPnlLayout = new javax.swing.GroupLayout(SpotifyPnl);
        SpotifyPnl.setLayout(SpotifyPnlLayout);
        SpotifyPnlLayout.setHorizontalGroup(
            SpotifyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );
        SpotifyPnlLayout.setVerticalGroup(
            SpotifyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );

        TabbedPane.addTab("Spotify", new javax.swing.ImageIcon(getClass().getResource("/spotify.png")), SpotifyPnl, "Spotify"); // NOI18N

        SettingsPnl.setBackground(LIGHT_BG);

        javax.swing.GroupLayout SettingsPnlLayout = new javax.swing.GroupLayout(SettingsPnl);
        SettingsPnl.setLayout(SettingsPnlLayout);
        SettingsPnlLayout.setHorizontalGroup(
            SettingsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );
        SettingsPnlLayout.setVerticalGroup(
            SettingsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );

        TabbedPane.addTab("Settings", new javax.swing.ImageIcon(getClass().getResource("/settings.png")), SettingsPnl); // NOI18N

        MainPanel.add(TabbedPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yt_BrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yt_BrowseBtnActionPerformed
        // TODO add your handling code here:
        browseOutputDirectory(yt_urlFld);
    }//GEN-LAST:event_yt_BrowseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderPnl;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel SettingsPnl;
    private javax.swing.JPanel SpotifyPnl;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JPanel YouTubeControlCard;
    private javax.swing.JPanel YouTubeInputCard;
    private javax.swing.JPanel YouTubePnl;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel subTitle;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JComboBox<String> yt_AudioQualityComBox;
    private javax.swing.JButton yt_BrowseBtn;
    private javax.swing.JPanel yt_DirPnl;
    private javax.swing.JPanel yt_OptionsPnl;
    private javax.swing.JTextField yt_OutputDirFld;
    private javax.swing.JLabel yt_OutputDirLbl;
    private javax.swing.JCheckBox yt_PlaylistCheckBox;
    private javax.swing.JTextField yt_urlFld;
    private javax.swing.JLabel yt_urlLbl;
    // End of variables declaration//GEN-END:variables
}
